services:
  - docker

language: go

dist: xenial

git:
  depth: false

go:
  - "1.15.x"

env:
  - KUBEBUILDER_ASSETS=$HOME/kubebuilder

cache:
  directories:
    - $HOME/gopath/pkg/mod

before_script:
  - docker --version
  - bash hack/install_kubebuilder.sh

script:
  - make lint-install
  - make test
  - make docker-build

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
    - make docker-build docker-push
  on:
    tags: true
