apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "secret-manager.fullname" . }}
  labels:
    {{- include "secret-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secret-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secret-manager.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secret-manager.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.healthCheck.enabled }}
          - --health-port={{ .Values.healthCheck.port }}
            {{- end }}
            {{- if .Values.prometheus.enabled }}
          - --metric-port={{ .Values.prometheus.service.port }}
            {{- end }}
            {{- if .Values.namespace }}
          - --namespace={{ .Values.namespace }}
            {{- end }}
            {{- if .Values.apiServerHost }}
          - --master={{ .Values.apiServerHost }}
            {{- end }}
            {{- if .Values.kubeConfig }}
          - --kubeconfig={{ .Values.kubeConfig }}
            {{- end }}
            {{- if .Values.leaderElect }}
          - --leader-elect=true
          - --leader-election-namespace={{ .Release.Namespace }}
            {{- else }}
          - --leader-elect=false
            {{- end }}
          {{- range $arg := .Values.extraArgs }}
          - {{ $arg }}
          {{- end }}
          env:
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.prometheus.enabled }}
          ports:
            - containerPort: {{.Values.prometheus.service.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthCheck.port }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.healthCheck.port }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
