replicaCount: 1

image:
  repository: secret-manager
  pullPolicy: IfNotPresent
  tag: "test"

installCRDs: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

apiServerHost: ""
kubeConfig: ""
namespace: ""
leaderElect: true

env:
  AWS_SECRETSMANAGER_ENDPOINT: "http://localstack"
  AWS_STS_ENDPOINT: "http://localstack"
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: foobar
  AWS_SECRET_ACCESS_KEY: foobar


serviceAccount:
  create: true
  annotations: {}
  name: ""

extraArgs: []

rbac:
  create: true

podLabels:
  app: secret-manager

podAnnotations:
  test: foobar

podSecurityContext: {}

securityContext: {}

healthCheck:
  enabled: true
  port: 8400

prometheus:
  enabled: true
  service:
    annotations: {}
    labels: {}
    port: 8711

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
